# Generated by Django 5.2.7 on 2025-10-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MutasiBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('description', models.CharField(max_length=150)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('kredit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mutasi Bank',
                'verbose_name_plural': 'Mutasi Bank',
                'db_table': 'mutasi_bank',
            },
        ),
        migrations.CreateModel(
            name='MutasiZahir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('ref_code', models.CharField(max_length=10)),
                ('ref_number', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=150)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('kredit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mutasi Zahir',
                'verbose_name_plural': 'Mutasi Zahir',
                'db_table': 'mutasi_zahir',
            },
        ),
    ]
